### ISSUE TITLE
URL für automatisches Einloggen?

### ISSUE THREAD

**Issue by Sahel2021** [vrootz/ep3-bs#1]
Hallo,
danke für dieses Autologin ! Ich habe das im Raspberry Pi 4 angelegt. Beim reboot öffnet Chromium im Kiosk Mode. Aber die vollständige Login-URL bringt die Fehlerseite von ep3 (Oops ... da ist wohl etwas schief gelaufen).
Die Zeile mit der URL in der kiosk.html lautet:

 <form method="post" name="lf" action="https://tcf-platzreservierung.de/&#x2F;buchung&#x2F;public&#x2F;user&#x2F;login?locale=de-DE" id="lf"> 

Was muss geändert werden?

**Comment by vrootz** [comment]
Hallo,

leider sehe ich die Zeile in der kiosk.html nicht, falls du die mir zeigen wolltest, die fehlt oben.
Es muss exakt die URL verwendet werden, wie die Domain als auch der Pfad in der die EP3 Software liegt aufgebaut ist.
Standardmäßig liegt die EP3 Software in /public/ abgelegt.
Beispielsweise:

Domain: tennis-gsv.de
Pfad: /buchung/public/

Das ergibt dann folgende URL:
https://tennis-gsv.de/buchung/public/user/login?locale=de-DE

<form method="post" name="lf" action="tennis-gsv.de/&#x2F;buchung&#x2F;public&#x2F;user&#x2F;login?locale=de-DE" id="lf">

Am besten ziehst du dir den HTML Schnipsel direkt aus deinem Browser von der Startseite heraus, passt die Zeilen dementsprechend an und löschst den nicht relevanten Teil. Dann ist das Encoding mit den "&#x2F"; auch kein Problem mehr.

Falls das nicht wirklich weiterhelfen sollte, dann kannst du mir ja mal die URL zu eurem Platzbuchungssystem schicken und dann kann ich mir das gerne anschauen.

**Comment by Sahel2021** [comment]
die URL ist https://tcf-platzreservierung.de/user/login?locale=de-DE

**Comment by vrootz** [comment]
Also wenn du die view-source:https://tcf-platzreservierung.de/user/login?locale=de-DE öffnest und dir die Zeile 92-109 anschaust, musst du die quasi nur noch anpassen, wie von mir beschrieben.
Ich habe das jetzt mal für dich gemacht, einfach nur noch die Values in der Datei mit den richtigen Logindaten anpassen.

https://github.com/vrootz/ep3-bs/blob/2be265dc7150bc3a974aa9beef33eeba10c9dda2/kiosk/issue_tcf

**Comment by Sahel2021** [comment]
Super, funktioniert jetzt. Vielen Dank! 
Habe das in unsere Doku aufgenommen: [TCF ep3](https://doku.tcf-platzreservierung.de/hardware/autologin-buchungssystem)
